# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  上帝之子
subtitle: 技术百态
name: jiangxuefeng
email: 1072254578@qq.com
description: 本站是技术分享博客。
keywords: ityouknow,纯洁的微笑,
encoding: "utf-8"
favicon: favicon.png 

repository: jiangxuefeng521/jiangxuefeng521.github.io
github_url: https://github.com/jiangxuefeng521
cnblog_url: http://www.cnblogs.com/jiangxuefeng521
url: https://jiangxuefeng521.github.io


## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home




# labels. my blog key words
labels:

  -
    href: /share/2017/10/01/resource-sharing.html
    name: 资源


# selected articles
classes:






# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

theme: jekyll-theme-merlot



